export const NAKSHATRAS = [
  {
    id: 'aswathi',
    en: 'Aswathi (Ashwini)',
    ml: 'അശ്വതി',
    deityEn: 'Lord Mahaganapathy & Lord Murugan',
    deityMl: 'മഹാഗണപതി & സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 4,
    offeringNameEn: 'Ganapathy Homam',
    offeringNameMl: 'ഗണപതി ഹോമം',
    significanceEn: 'Auspicious beginnings, removal of delays and vitality.',
    significanceMl: 'കാര്യവിജയത്തിനും വിഘ്നനിവാരണത്തിനും ഉത്തമം.'
  },
  {
    id: 'bharani',
    en: 'Bharani',
    ml: 'ഭരണി',
    deityEn: 'Bhadrakali & Lord Murugan',
    deityMl: 'ഭദ്രകാളി & മുരുകൻ',
    recommendedOfferingId: 5,
    offeringNameEn: 'Shatrusamhara Pushpanjali',
    offeringNameMl: 'ശത്രുസംഹാര പുഷ്പാഞ്ജലി',
    significanceEn: 'Protection from negative energies, courage and willpower.',
    significanceMl: 'ദുരിതശാന്തിക്കും ശത്രുദോഷ നിവാരണത്തിനും.'
  },
  {
    id: 'karthika',
    en: 'Karthika (Krittika)',
    ml: 'കാർത്തിക',
    deityEn: 'Lord Subramanya (Birth Star of Murugan)',
    deityMl: 'ശ്രീ സുബ്രഹ്മണ്യസ്വാമി (മുരുകന്റെ ജന്മനക്ഷത്രം)',
    recommendedOfferingId: 7,
    offeringNameEn: 'Panchamrutham & Palabhishekam',
    offeringNameMl: 'പഞ്ചാമൃതം & പാലഭിഷേകം',
    significanceEn: 'Supreme grace of Lord Murugan, radiance, health and prosperity.',
    significanceMl: 'മുരുകന്റെ വിശേഷ കൃപയ്ക്കും കുടുംബ ഐശ്വര്യത്തിനും ഉത്തമം.'
  },
  {
    id: 'rohini',
    en: 'Rohini',
    ml: 'രോഹിണി',
    deityEn: 'Lord Mahaganapathy & Murugan',
    deityMl: 'മഹാഗണപതി & ബാലമുരുകൻ',
    recommendedOfferingId: 3,
    offeringNameEn: 'Nai Payasam Samarpanam',
    offeringNameMl: 'നെയ്പായസം സമർപ്പണം',
    significanceEn: 'Artistic creativity, peace of mind and family bliss.',
    significanceMl: 'മനശ്ശാന്തിക്കും കുടുംബ സൗഖ്യത്തിനും അഭീഷ്ടസിദ്ധിക്കും.'
  },
  {
    id: 'makayiram',
    en: 'Makayiram (Mrigashirsha)',
    ml: 'മകയിരം',
    deityEn: 'Lord Subramanya',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 8,
    offeringNameEn: 'Bhasmabhishekam & Archana',
    offeringNameMl: 'ഭസ്മാഭിഷേകം & അർച്ചന',
    significanceEn: 'Clarity of mind, career stability and spiritual upliftment.',
    significanceMl: 'കർമ്മമേഖലയിലെ ഉയർച്ചയ്ക്കും ആത്മീയ ശാന്തിക്കും.'
  },
  {
    id: 'thiruvathira',
    en: 'Thiruvathira (Ardra)',
    ml: 'തിരുവാതിര',
    deityEn: 'Lord Mahadeva (Shiva)',
    deityMl: 'മഹാദേവൻ (ശിവൻ)',
    recommendedOfferingId: 9,
    offeringNameEn: 'Jala Dhara & Palabhishekam',
    offeringNameMl: 'ധാര & പാലഭിഷേകം',
    significanceEn: 'Relief from sorrow, health, and longevity under Lord Shiva.',
    significanceMl: 'ആയുരാരോഗ്യത്തിനും ആധിവ്യാധികൾ അകലുന്നതിനും.'
  },
  {
    id: 'punartham',
    en: 'Punartham (Punarvasu)',
    ml: 'പുണർതം',
    deityEn: 'Lord Subramanya & Ganapathy',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി & ഗണപതി',
    recommendedOfferingId: 1,
    offeringNameEn: 'Bhagya Sooktha Pushpanjali',
    offeringNameMl: 'ഭാഗ്യസൂക്ത പുഷ്പാഞ്ജലി',
    significanceEn: 'Return of lost prosperity, harmony and good fortune.',
    significanceMl: 'ഭാഗ്യവർദ്ധനവിനും നഷ്ടസൗഭാഗ്യങ്ങൾ വീണ്ടെടുക്കുന്നതിനും.'
  },
  {
    id: 'pooyam',
    en: 'Pooyam (Pushya)',
    ml: 'പൂയം',
    deityEn: 'Lord Subramanya (Thai Pooyam Star)',
    deityMl: 'ശ്രീ സുബ്രഹ്മണ്യസ്വാമി (തൈപ്പൂയ നക്ഷത്രം)',
    recommendedOfferingId: 7,
    offeringNameEn: 'Maha Panchamrutham & Vel Pooja',
    offeringNameMl: 'പഞ്ചാമൃതം & വേൽ പൂജ',
    significanceEn: 'Highest spiritual realization, wisdom, and victory over all obstacles.',
    significanceMl: 'വിദ്യാവിജയത്തിനും ആഗ്രഹസാഫല്യത്തിനും സർവ്വവിജയത്തിനും.'
  },
  {
    id: 'aayilyam',
    en: 'Aayilyam (Ashlesha)',
    ml: 'ആയില്യം',
    deityEn: 'Nagaraja & Nagadevathas',
    deityMl: 'നാഗരാജാവ് & നാഗദൈവങ്ങൾ',
    recommendedOfferingId: 9,
    offeringNameEn: 'Noorum Palum & Palabhishekam',
    offeringNameMl: 'നൂറും പാലും & പാലഭിഷേകം',
    significanceEn: 'Complete pacification of Sarpa Dosha, lineage growth and skin health.',
    significanceMl: 'സർപ്പദോഷ ശമനത്തിനും സന്താനലബ്ധിക്കും ത്വക്ക് രോഗശാന്തിക്കും.'
  },
  {
    id: 'makam',
    en: 'Makam (Magha)',
    ml: 'മകം',
    deityEn: 'Balamurugan & Pitru Devathas',
    deityMl: 'ബാലമുരുകൻ & ഭഗവതി',
    recommendedOfferingId: 3,
    offeringNameEn: 'Kadumpayasam & Deeparadhana',
    offeringNameMl: 'കടുംപായസം & ദീപാരാധന',
    significanceEn: 'Ancestral blessings, leadership and social prosperity.',
    significanceMl: 'പിതൃപ്രീതിക്കും സമൂഹത്തിൽ കീർത്തിക്കും ഐശ്വര്യത്തിനും.'
  },
  {
    id: 'pooram',
    en: 'Pooram (Purva Phalguni)',
    ml: 'പൂരം',
    deityEn: 'Bhagavathy & Lord Murugan',
    deityMl: 'ഭഗവതി & സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 1,
    offeringNameEn: 'Kunkumarchana & Pushpanjali',
    offeringNameMl: 'കുങ്കുമാർച്ചന & പുഷ്പാഞ്ജലി',
    significanceEn: 'Marital bliss, joy, and harmonious relationships.',
    significanceMl: 'വിവാഹതടസ്സങ്ങൾ മാറുന്നതിനും ദാമ്പത്യസൗഖ്യത്തിനും.'
  },
  {
    id: 'uthram',
    en: 'Uthram (Uttara Phalguni)',
    ml: 'ഉത്രം',
    deityEn: 'Lord Murugan & Sastha',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി & അയ്യപ്പൻ',
    recommendedOfferingId: 2,
    offeringNameEn: 'Muttarukkal & Archana',
    offeringNameMl: 'മുട്ടറുക്കൽ & അർച്ചന',
    significanceEn: 'Removal of planetary hindrances and career elevation.',
    significanceMl: 'ഗ്രഹദോഷ ശമനത്തിനും തൊഴിൽ തടസ്സങ്ങൾ മാറുന്നതിനും.'
  },
  {
    id: 'atham',
    en: 'Atham (Hasta)',
    ml: 'അത്തം',
    deityEn: 'Lord Mahaganapathy',
    deityMl: 'മഹാഗണപതി',
    recommendedOfferingId: 4,
    offeringNameEn: 'Ashtadravya Ganapathy Homam',
    offeringNameMl: 'അഷ്ടദ്രവ്യ ഗണപതി ഹോമം',
    significanceEn: 'Skill, trade success, mental agility and good health.',
    significanceMl: 'വ്യാപാര അഭിവൃദ്ധിക്കും ബുദ്ധിവൈഭവത്തിനും.'
  },
  {
    id: 'chithira',
    en: 'Chithira (Chitra)',
    ml: 'ചിത്തിര',
    deityEn: 'Lord Murugan (Karthikeya)',
    deityMl: 'ശ്രീ സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 10,
    offeringNameEn: 'Chuttuvilakku Deepam',
    offeringNameMl: 'ചുറ്റുവിളക്ക് ദീപം',
    significanceEn: 'Removal of gloom, radiance of personality and fame.',
    significanceMl: 'ജീവിതത്തിൽ പ്രകാശവും പ്രശസ്തിയും കൈവരുന്നതിന്.'
  },
  {
    id: 'chothi',
    en: 'Chothi (Swati)',
    ml: 'ചോതി',
    deityEn: 'Lord Murugan & Bhagavathy',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി & ഭഗവതി',
    recommendedOfferingId: 1,
    offeringNameEn: 'Swayamvara Pushpanjali',
    offeringNameMl: 'സ്വയംവര പുഷ്പാഞ്ജലി',
    significanceEn: 'Swift marital alliances, peace, and spiritual growth.',
    significanceMl: 'വിവാഹയോഗത്തിനും മനശ്ശാന്തിക്കും.'
  },
  {
    id: 'vishakam',
    en: 'Vishakam (Vishakha)',
    ml: 'വിശാഖം',
    deityEn: 'Lord Subramanya (Vaikasi Visakam Avatar)',
    deityMl: 'ശ്രീ സുബ്രഹ്മണ്യസ്വാമി (മുരുക അവതാര നക്ഷത്രം)',
    recommendedOfferingId: 7,
    offeringNameEn: 'Panchamrutham & Vel Archana',
    offeringNameMl: 'പഞ്ചാമൃതം & വേൽ അർച്ചന',
    significanceEn: 'Supreme triumph over all difficulties, high goals attainment.',
    significanceMl: 'സകല ദുരിതങ്ങളിൽ നിന്നുമുള്ള മോചനത്തിനും ഉന്നത വിജയത്തിനും.'
  },
  {
    id: 'anizham',
    en: 'Anizham (Anuradha)',
    ml: 'അനിഴം',
    deityEn: 'Lord Shiva & Murugan',
    deityMl: 'മഹാദേവൻ & സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 9,
    offeringNameEn: 'Ksheera Dhara & Pushpanjali',
    offeringNameMl: 'ക്ഷീരധാര & പുഷ്പാഞ്ജലി',
    significanceEn: 'Devotion, long life, and relief from Saturn (Shani) doshas.',
    significanceMl: 'ശനിദോഷ ശാന്തിക്കും ദീർഘായുസ്സിനും ആത്മശാന്തിക്കും.'
  },
  {
    id: 'thrikketta',
    en: 'Thrikketta (Jyeshtha)',
    ml: 'തൃക്കേട്ട',
    deityEn: 'Lord Mahaganapathy & Nagaraja',
    deityMl: 'മഹാഗണപതി & നാഗരാജാവ്',
    recommendedOfferingId: 4,
    offeringNameEn: 'Ganapathy Homam & Archana',
    offeringNameMl: 'ഗണപതി ഹോമം & അർച്ചന',
    significanceEn: 'Protection of family assets, courage and shielding against enmity.',
    significanceMl: 'കുടുംബ സംരക്ഷണത്തിനും ശത്രുഭയം മാറുന്നതിനും.'
  },
  {
    id: 'moolam',
    en: 'Moolam (Mula)',
    ml: 'മൂലം',
    deityEn: 'Lord Subramanya & Mahadeva',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി & പരമശിവൻ',
    recommendedOfferingId: 8,
    offeringNameEn: 'Bhasmabhishekam & Mrityunjaya Archana',
    offeringNameMl: 'ഭസ്മാഭിഷേകം & മൃത്യുഞ്ജയ അർച്ചന',
    significanceEn: 'Root cure of persistent physical and mental troubles.',
    significanceMl: 'ദീർഘകാല രോഗശാന്തിക്കും ദോഷപരിഹാരത്തിനും.'
  },
  {
    id: 'pooradam',
    en: 'Pooradam (Purva Ashadha)',
    ml: 'പൂരാടം',
    deityEn: 'Bhagavathy & Lord Murugan',
    deityMl: 'ഭഗവതി & സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 3,
    offeringNameEn: 'Nai Payasam & Deeparadhana',
    offeringNameMl: 'നെയ്പായസം & ദീപാരാധന',
    significanceEn: 'Abundance in home, inner poise and unshakeable confidence.',
    significanceMl: 'ഭവനത്തിൽ ഐശ്വര്യവും ആത്മവിശ്വാസവും നിറയുവാൻ.'
  },
  {
    id: 'uthradam',
    en: 'Uthradam (Uttara Ashadha)',
    ml: 'ഉത്രാടം',
    deityEn: 'Lord Mahaganapathy & Murugan',
    deityMl: 'ഗണപതി & ബാലമുരുകൻ',
    recommendedOfferingId: 1,
    offeringNameEn: 'Sahasranama Pushpanjali',
    offeringNameMl: 'സഹസ്രനാമ പുഷ്പാഞ്ജലി',
    significanceEn: 'Infallible victory in endeavors and noble reputation.',
    significanceMl: 'കർമ്മരംഗത്തെ അസൂയാവഹമായ വിജയത്തിനും കീർത്തിക്കും.'
  },
  {
    id: 'thiruvonam',
    en: 'Thiruvonam (Shravana)',
    ml: 'തിരുവോണം',
    deityEn: 'Lord Subramanya & Mahavishnu',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി & വിഷ്ണു',
    recommendedOfferingId: 11,
    offeringNameEn: 'Vidyarambham & Archana',
    offeringNameMl: 'വിദ്യാരംഭ പൂജ & അർച്ചന',
    significanceEn: 'Knowledge retention, eloquence, and all-round auspiciousness.',
    significanceMl: 'വിദ്യാഭിവൃദ്ധിക്കും വാക്‌സാമർത്ഥ്യത്തിനും കുടുംബൈശ്വര്യത്തിനും.'
  },
  {
    id: 'avittom',
    en: 'Avittom (Dhanishta)',
    ml: 'അവിട്ടം',
    deityEn: 'Lord Murugan',
    deityMl: 'സുബ്രഹ്മണ്യസ്വാമി',
    recommendedOfferingId: 5,
    offeringNameEn: 'Shatrusamhara Pushpanjali',
    offeringNameMl: 'ശത്രുസംഹാര പുഷ്പാഞ്ജലി',
    significanceEn: 'Courage, wealth accumulation, and conquering hardships.',
    significanceMl: 'സാമ്പത്തിക അഭിവൃദ്ധിക്കും ആപത്തുകളിൽ നിന്നുള്ള രക്ഷയ്ക്കും.'
  },
  {
    id: 'chathayam',
    en: 'Chathayam (Shatabhisha)',
    ml: 'ചതയം',
    deityEn: 'Lord Shiva & Nagadevathas',
    deityMl: 'പരമശിവൻ & നാഗദൈവങ്ങൾ',
    recommendedOfferingId: 9,
    offeringNameEn: 'Dhara & Palabhishekam',
    offeringNameMl: 'ധാര & പാലഭിഷേകം',
    significanceEn: 'Healing of chronic ailments and spiritual transcendence.',
    significanceMl: 'സകല രോഗശാന്തിക്കും ദീർഘായുസ്സിനും.'
  },
  {
    id: 'poororuttathi',
    en: 'Poororuttathi (Purva Bhadrapada)',
    ml: 'പൂരുരുട്ടാതി',
    deityEn: 'Lord Shiva & Subramanya',
    deityMl: 'ശിവൻ & സുബ്രഹ്മണ്യൻ',
    recommendedOfferingId: 8,
    offeringNameEn: 'Bhasmabhishekam',
    offeringNameMl: 'ഭസ്മാഭിഷേകം',
    significanceEn: 'Relief from anxiety, ethical wealth, and peace of mind.',
    significanceMl: 'മാനസിക പിരിമുറുക്കങ്ങൾ അകലുന്നതിനും സമാധാനത്തിനും.'
  },
  {
    id: 'uthrattathi',
    en: 'Uthrattathi (Uttara Bhadrapada)',
    ml: 'ഉത്രട്ടാതി',
    deityEn: 'Lord Murugan (Temple Annual Festival Star)',
    deityMl: 'ശ്രീ സുബ്രഹ്മണ്യസ്വാമി (ക്ഷേത്ര ഉത്സവനക്ഷത്രം)',
    recommendedOfferingId: 7,
    offeringNameEn: 'Maha Panchamrutham & Annadanam',
    offeringNameMl: 'മഹാ പഞ്ചാമൃതം & അന്നദാനം',
    significanceEn: 'Highest benediction, deep spiritual peace, and temple deity resonance.',
    significanceMl: 'ക്ഷേത്ര പ്രതിഷ്ഠാ ദിന കൃപയ്ക്കും കുടുംബത്തിന്റെ സർവ്വതോന്മുഖമായ ഉയർച്ചയ്ക്കും.'
  },
  {
    id: 'revathi',
    en: 'Revathi',
    ml: 'രേവതി',
    deityEn: 'Lord Mahaganapathy & Murugan',
    deityMl: 'മഹാഗണപതി & മുരുകൻ',
    recommendedOfferingId: 4,
    offeringNameEn: 'Modaka Ganapathy Homam',
    offeringNameMl: 'മോദക ഗണപതി ഹോമം',
    significanceEn: 'Prosperous journeys, safe ventures, and wholesome happiness.',
    significanceMl: 'യാത്രാവിജയത്തിനും സൗഭാഗ്യത്തിനും സുഖകരമായ ജീവിതത്തിനും.'
  }
];
